default: &default
  path: 10.245.162.58
  supported_combinations:
    trusty:
    - mitaka
    xenial:
    - mitaka
    - newton
    - ocata
    - pike
    - queens
    bionic:
    - queens
    - rocky
    - stein
    cosmic:
    - rocky
    disco:
    - stein

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
